# Generated by Django 2.1.7 on 2019-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(default='Delicious Carrot Cake', max_length=200),
            preserve_default=False,
        ),
    ]
