# Generated by Django 2.1.7 on 2019-03-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0003_auto_20190306_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g.', 'Gram'), ('Kg.', 'Kilogram'), ('cl.', 'Centiliter'), ('l.', 'Liter')], default='g.', max_length=2),
        ),
    ]
